// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyioattkozmbvcuqhaij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aW9hdHRrb3ptYnZjdXFoYWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzOTQwNDgsImV4cCI6MjA1Nzk3MDA0OH0.yoqsD0gdBONbL76xUABcRtDFWEgcO9r_Nk2LT_emokU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);